### ISSUE TITLE
Add jQuery 2.0

### ISSUE THREAD

**Issue by ghost** [contao-components/jquery#1]
<a href="https://github.com/DyaGa"><img src="https://avatars.githubusercontent.com/u/101594?v=3" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core/issues/5725) by @DyaGa
May 3rd, 2013, 22:53 GMT

Add jQuery 2.0 version for those users who do not want support Internet Explorer 6, 7, or 8.

So, in this case we should have to jQuery versions: 1.9.1 and 2.0

**Comment by leofeyer** [comment]
I have added jQuery 2 in the [feature/2.x](https://github.com/contao-components/jquery/tree/feature/2.x) branch. To require it, add the following line to your project's `composer.json`:

``` json
"require": {
    "contao-components/jquery": "~2.1"
}
```
