### ISSUE TITLE
update jquery

### ISSUE THREAD

**Issue by jonnysp** [contao-components/jquery#2]
hi leo
kannst du jquery aktualisieren oder einen versions selektor einbauen?

grüße jonny

**Comment by leofeyer** [comment]
Es gibt bereits Zweige für jQuery 2 und 3. Eigentlich hatten wir es so gedacht, dass man in seiner `composer.json` folgendes schreibt:

```json
"require": {
    "contao-components/jquery": "^2.0"
}
```

Allerdings ist das Requirement inzwischen im Core-Bundle, daher geht das so nicht mehr:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - contao/core-bundle 4.4.5 requires contao-components/jquery ^1.11.3 -> satisfiable by contao-components/jquery[1.11.3, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4] but these conflict with your requirements or minimum-stability.
    - contao/core-bundle 4.4.5 requires contao-components/jquery ^1.11.3 -> satisfiable by contao-components/jquery[1.11.3, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4] but these conflict with your requirements or minimum-stability.
    - contao/core-bundle 4.4.5 requires contao-components/jquery ^1.11.3 -> satisfiable by contao-components/jquery[1.11.3, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4] but these conflict with your requirements or minimum-stability.
    - Installation request for contao/core-bundle (locked at 4.4.5, required as ^4.4) -> satisfiable by contao/core-bundle[4.4.5].
```

Du könntest Composer überlisten, indem Du folgendes konfigurierst:

```json
"require": {
    "contao-components/jquery": "dev-feature/2.x as 1.12.4",
}
```

Aber am einfachsten wäre es eigentlich, wenn wir die jQuery-Skripte im Core einfach mit allen Versionen kompatibel machen und dann `"contao-components/jquery": "@stable"` anfordern würden.

@ausi @aschempp /cc

**Comment by ausi** [comment]
Ich denke wir sollte das Core-Bundle nur mit jQuery-Versionen kompatibel machen mit der die Skripts aus dem Core-Bundle getestet wurden, nicht mit allen Versionen. z.B: `"contao-components/jquery": "^1.11.3,^2.0"`

**Comment by leofeyer** [comment]
Das wäre dann `^1.11.3,^2.0,^3.0`. Allerdings müsste ich die Skripte noch mit Version 2 und 3 testen. 😄

**Comment by aschempp** [comment]
Grundsätzlich einverstanden, es würde aber halt zu einem jQuery Update führen und damit alle bestehenden Systeme beeinflussen…

**Comment by leofeyer** [comment]
Stimmt, das ist nicht so optimal.

**Comment by ausi** [comment]
Sollten wir dann erst in der 4.5 machen denke ich.

**Comment by leofeyer** [comment]
Die Alternative wäre es, die jQuery-Version nur in der Edition zu definieren, so ähnlich wie es jetzt mit dem Guzzle6-Adapter ist.

**Comment by aschempp** [comment]
> Die Alternative wäre es, die jQuery-Version nur in der Edition zu definieren

Finde ich auch nicht unbedingt richtig. Eigentlich ist es doch so, dass die jQuery-Version nicht zur Installation, sondern mit dem Theme zu tun hat? Eigentlich sollte ich ihm Theme doch die jQuery-Version auswählen können? Also z.B. jQuery 1/2/3 aus CDN oder aus mehreren lokal installierten?

**Comment by leofeyer** [comment]
@aschempp @ausi Was machen wir denn jetzt? `^1.11.3,^2.0,^3.0` oder alle Versionen laden und per Checkbox auswählen?

**Comment by ausi** [comment]
Mehrere Versionen ist aus meiner Sicht nicht nötig und wäre auch nicht einfach umsetzbar via Composer, oder?

Ich bin dafür in Contao 4.6 im core-bundle das constraint auf `^1.11.3,^2.0,^3.0` zu ändern. In dem Zuge sollte wir natürlich testen ob auch tatsächlich alles funktioniert mit jQuery 2 und 3.

**Comment by agoat** [comment]
Meine erste Idee war auch einen jQuery Selector einzubauen und jeder kann sich seine Version raussuchen. Das würde aber bedeuten, man müsste im `contao-components/jquery` Paket alle Versionen in unterschiedlichen Verzeichnissen reinpacken.

Mittlerweile gehe ich aber einen anderen Weg und benutze gar nicht mehr jQuery oder MooTools aus dem Contao Framwork, sondern speichere mir die entsprechende Version als Datei und füge diese hinzu (seit JS-Dateien im Layout eingebunden werden können ist es noch einfacher).

> Ich bin dafür in Contao 4.6 im core-bundle das constraint auf ^1.11.3,^2.0,^3.0 zu ändern.

@ausi Ist es damit dann möglich die jQuery Version in der Projekt composer.json zu definieren?

**Comment by ausi** [comment]
@agoat Ja ist es. Standardmäßig wird dann die neuste jQuery-Version benutzt aber mit z. B. `"contao-components/jquery":"^2.0"` kannst du explizit auf die neueste 2er Version downgraden.

**Comment by leofeyer** [comment]
Ich habe alle jQuery-Plugins überprüft und abgesehen von ein paar Deprecations laufen alle mit jQuery 2 und 3. Ich habe daher das Version-Constraint in contao/core-bundle@c10b9ccec1c34385686c8045a296d1e70def9d5b angepasst.

<img width="715" alt="" src="https://user-images.githubusercontent.com/1192057/42306947-286b3546-8031-11e8-8814-1cd9015fd44a.png">
